`line 2 "butterfly_in_tlv.tlv" 0 //_\TLV_version 1d: tl-x.org, generated by SandPiper(TM) 1.14-2022/10/10-beta-Pro
`line 11 "butterfly_in_tlv.tlv" 1
//_\SV
   // Macro providing required top-level module definition, random
   // stimulus support, and Verilator config.
   //module top(input wire clk, input wire reset, input wire [31:0] cyc_cnt, output wire passed, output wire failed);    /* verilator lint_save */ /* verilator lint_off UNOPTFLAT */  bit [256:0] RW_rand_raw; bit [256+63:0] RW_rand_vect; pseudo_rand #(.WIDTH(257)) pseudo_rand (clk, reset, RW_rand_raw[256:0]); assign RW_rand_vect[256+63:0] = {RW_rand_raw[62:0], RW_rand_raw};  /* verilator lint_restore */  /* verilator lint_off WIDTH */ /* verilator lint_off UNOPTFLAT */   // (Expanded in Nav-TLV pane.)

	module top
   #(parameter ADDR_W = 4)
      (
     input wire clk,
     input wire reset_n,
     input wire [31:0] a,
     input wire [31:0] b,
     input wire [ADDR_W-1:0] tw_addr,
     output wire [31:0] c_plus,
     output wire [31:0] c_minus
   );
`line 50 "butterfly_in_tlv.tlv" 1


`include "butterfly_in_tlv_gen.sv" //_\TLV
   //_|butterfly1
      //_@0
         //$A[31:0] = 32'h00010001;
         //$B[31:0] = 32'h00020002;
         //$W[31:0] = 32'hff4b00b5;
         assign BUTTERFLY1_a_a0[31:0] = a;
         assign BUTTERFLY1_b_a0[31:0] = b;
         assign BUTTERFLY1_addr_a0[3:0] = tw_addr;
      //after 6 delay stages
      //_@8
         assign c_plus = BUTTERFLY1_c_a8;
         assign c_mius = BUTTERFLY1_d_a8;

      `line 28 "butterfly_in_tlv.tlv" 1   // Instantiated from butterfly_in_tlv.tlv, 66 as: m4+dif_butterfly(@1)
         //Butterfly Unit for RADIX-2 DIF FFT
         // C = A + B
         // D = W(A - B)
         // Dividing Complex multiplciations into real and imaginary parts
         // Cr = Ar + Br
         // Ci = Ai + Bi
         // Dr = Wr*(Ar - Br) - Wi*(Ai - Bi)
         // Di = Wr*(Ai - Bi) + Wi*(Ar - Br)
         //_@1
            /*SV_plus*/
               wire [31:0] twiddles [0:3];
               assign twiddles[0] = 32'h00000100;
               assign twiddles[1] = 32'hFF4B00B5;
               assign twiddles[2] = 32'hFF000000;
               assign twiddles[3] = 32'hFF4BFF4B;
            assign BUTTERFLY1_w_a1[31:0] = twiddles[$addr];
            assign BUTTERFLY1_cr_a1[15:0] = BUTTERFLY1_a_a1[31:16] + BUTTERFLY1_a_a1[31:16];
            assign BUTTERFLY1_ci_a1[15:0] = BUTTERFLY1_a_a1[15:0] + BUTTERFLY1_b_a1[15:0];
            assign BUTTERFLY1_dr_a1[15:0] = BUTTERFLY1_w_a1[31:16]*(BUTTERFLY1_a_a1[31:16] - BUTTERFLY1_b_a1[31:16]) - BUTTERFLY1_w_a1[15:0]*(BUTTERFLY1_a_a1[15:0] - BUTTERFLY1_b_a1[15:0]);
            assign BUTTERFLY1_di_a1[15:0] = BUTTERFLY1_w_a1[31:16]*(BUTTERFLY1_a_a1[15:0] - BUTTERFLY1_b_a1[15:0]) + BUTTERFLY1_w_a1[15:0]*(BUTTERFLY1_a_a1[31:16] - BUTTERFLY1_b_a1[31:16]);
            assign BUTTERFLY1_c_a1[31:0] = {BUTTERFLY1_cr_a1,BUTTERFLY1_ci_a1};
            assign BUTTERFLY1_d_a1[31:0] = {BUTTERFLY1_dr_a1,BUTTERFLY1_di_a1};
      //_\end_source
      `line 67 "butterfly_in_tlv.tlv" 2

//_\SV
   endmodule



// Undefine macros defined by SandPiper (in "butterfly_in_tlv_gen.sv").
`undef BOGUS_USE
